# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [angelsflyinhell]
patreon: # Replace with a single angelsflyinhell
ko_fi: # Replace with a single Ko-fi azamivisuals
